### ISSUE TITLE
Are you open to pull requests ? (custom width/height fonts)

### ISSUE THREAD

**Issue by berdal84** [BalazsJako/ImGuiColorTextEdit#29] opened 2018-06-03 17:12 UTC
I'm working on a tool, if you're interested: https://github.com/berdal84/Nodable/
I would like to be able to use your imGuiColorTextEdit with custom width/height fonts. 
I'll be happy to contribute by adding custom font handling, are you open to it ? If yes, any suggestions to do it before I start ?

A capture of your ImGuiColorTextEdit integrated into my app :
https://github.com/berdal84/Nodable/blob/texteditor/screenshots/2018_06_03_Testing_ImGuiColorTextEdit.png

**Comment by berdal84** [comment] 2018-06-03 20:42
I started something this evening : https://github.com/berdal84/ImGuiColorTextEdit/commits/custom_font
It is working fine except when scaling up font (Ctrl + mouse wheel).

**Comment by berdal84** [comment] 2018-06-04 20:24
I just finished to modify your code to be able to scale fonts with Ctrl + mouse wheel. It works great:
https://github.com/berdal84/ImGuiColorTextEdit/commits/custom_font

**Comment by berdal84** [comment] 2018-06-04 23:42
Your ColorTextEdit is now well integrated into my app : https://raw.githubusercontent.com/berdal84/Nodable/texteditor/screenshots/2018_06_05_With_ImGuiColorTextEdit.png
I hope you're still looking at your GitHub messages... Bye.

**Comment by BalazsJako** [comment] 2018-06-07 09:54
Hi, nice work. Yes, why not, it looks fine to me, and seems to be simple enough. Have you checked it against the old fixed-widrh fonts setups?

**Comment by berdal84** [comment] 2018-06-07 13:28
I just check it and there are two small problem:
- line numbers. I don't know why but numbers are right aligned  too close from line start. I have an idea to fix that. Maybe line could starts at a position that  could be deduced from lineNo max as text width.
- tabs. I think I drop them.

Let me fix these two problems and rearrange the commits to make the PR easy to read.

**Comment by BalazsJako** [comment] 2018-06-07 14:43
Line numbers are right aligned by design. The editors I used as reference are all render line numbers right aligned.

Tabs probably should be fixed size. Try checking Notepad++ or VS editors and see what they do when variable width fonts are used.

**Comment by BalazsJako** [comment] 2018-09-05 22:26
I've merged it all, and fixed all the issues I found in the wake of it. Font scaling is still not working precisely. Variable-width fonts are OK now.

**Closed by BalazsJako** 2018-09-05 22:26 UTC
